language: java
jdk:
- oraclejdk8

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

after_success:
  - gradle uploadArchives -Psnapshot -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
